name: Prebuild

on:
  push:
  workflow_dispatch:

concurrency:
  group: prebuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prebuild-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: node -v
      - run: pnpm -v

      - name: Clear pnpm cache
        run: pnpm store prune
      - run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm prebuild --arch x64

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: prebuilds

  prebuild-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: node -v
      - run: pnpm -v

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxrandr-dev \
            libxtst-dev \
            libxi-dev \
            libxinerama-dev

      - name: Clear pnpm cache
        run: pnpm store prune
      - run: pnpm install --frozen-lockfile

      - run: pnpm prebuild --arch x64
      - run: pnpm prebuild --arch arm64

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: prebuilds

  prebuild-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: node -v
      - run: pnpm -v

      - name: Clear pnpm cache
        run: pnpm store prune
      - run: pnpm install --frozen-lockfile

      - run: pnpm prebuild --arch x64
      - run: pnpm prebuild --arch arm64

      - uses: actions/upload-artifact@v4
        with:
          name: darwin
          path: prebuilds

  build-package:
    needs:
      - prebuild-windows
      - prebuild-linux
      - prebuild-darwin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: prebuilds

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: node -v
      - run: pnpm -v

      - name: Clear pnpm cache
        run: pnpm store prune
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm build-ts
      - run: npm pack

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: "mukea-uiohook-napi-*.tgz"
