name: Prebuild

on:
  push:
  workflow_dispatch:
concurrency:
  group: prebuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prebuild-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: npm install -g node-gyp

      - run: yarn apply-libuiohook-patch

      - run: yarn --frozen-lockfile --ignore-scripts

      - run: yarn prebuild --arch x64

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: prebuilds


  prebuild-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxrandr-dev \
            libxtst-dev \
            libxi-dev \
            libxinerama-dev

      - run: yarn apply-libuiohook-patch

      - run: yarn --frozen-lockfile

      - run: yarn prebuild --arch x64
      - run: yarn prebuild --arch arm64

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: prebuilds


  prebuild-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn apply-libuiohook-patch

      - run: yarn --frozen-lockfile

      - run: yarn prebuild --arch x64
      - run: yarn prebuild --arch arm64

      - uses: actions/upload-artifact@v4
        with:
          name: darwin
          path: prebuilds


  build-package:
    needs:
      - prebuild-windows
      - prebuild-linux
      - prebuild-darwin

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/download-artifact@v4
        with:
          path: prebuilds

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn apply-libuiohook-patch

      - run: yarn --frozen-lockfile --ignore-scripts

      - run: yarn build-ts

      - run: npm pack

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: "mukea-uiohook-napi-*.tgz"